#!/bin/bash

## common stuff
RED='\033[0;101m'
GREEN='\033[0;102m'
NC='\033[0m'

logline () {
	echo -e "${GREEN} >>>> $1           ${NC}"
}

## grep some info out of the os-release file
OS_ID=$(grep -oP '(?<=^ID=).+' /etc/os-release | tr -d '"')
OS_VERSION=$(grep -oP '(?<=^VERSION_ID=).+' /etc/os-release | tr -d '"')
# Use 80,81,82,83,84 etc
PHPVER=83
#NODEVER=16.17.1
NODEVER=24
INSTALLPWD=`pwd`

