#!/bin/bash

. ${BASH_SOURCE%/*}/00_settings

logline "01.00 user create START"
while [ -z "$username" ]; do
	echo -n "Enter username to create and setup as sudoer =>" && read username
done

while [ -z "$pubkey" ]; do
        echo "Paste your public key for ssh access"
        read pubkey
done 

export username

logline "01.01 add user"
## add the user and lock the password
adduser $username -m -n && passwd $username -l

logline "01.02 setup ssh, bin and some settings"
## set user's ssh
su $username <<-'EOF'
        mkdir ~/.ssh/
        touch ~/.ssh/authorized_keys && chmod 0600 ~/.ssh/authorized_keys
        # add deploy key for the machine
        ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa

        chmod 0700 ~/.ssh

	# lets make a ~/bin and add it to the path
	mkdir ~/bin
        echo "export PATH=\$PATH:~/bin" >> ~/.bashrc

        ## get rid of unreadable vim colorcoding
        echo -e "syntax off\nset t_ti= t_te= \n" >> ~/.vimrc
EOF
echo -e "\n$pubkey\n" >>/home/$username/.ssh/authorized_keys

logline "01.06 add $username to sudoers"
## add user to sudoers
chmod u+w /etc/sudoers
echo "$username         ALL=(ALL) NOPASSWD:     ALL" >>/etc/sudoers
chmod u-w /etc/sudoers

logline "01.99 user create END"

