#!/bin/bash

. ${BASH_SOURCE%/*}/00_settings

logline "04.00 start root security"
logline "04.01 secure password or locked password"
echo -n "Do you want a long secure root password (l) or no password at all (n) [L/n]=>" && read rootpas
if [ "$rootpas" = "n" ]; then 
	passwd root -l	
else
	## create long (emergency) password for root
	newpas=`tr -dc A-Z-a-z0-9 < /dev/urandom | head -c${1:-32}`
	echo $newpas | passwd root --stdin
	echo ">>>>>>>>> ROOT password set to $newpas - you might want to write this down"
	echo -n "Enter to continue >" && read 
fi
logline "04.99 root secured"


