#!/bin/bash

. ${BASH_SOURCE%/*}/00_settings

logline "06.00 global settings START"
# color prompt
logline "06.01 color prompt"
echo 'export PS1="\[\e[31;1m\]\h \[\e[0;34m\]\w\[\e[39m\] \[\e[0;32m\]\u\[\e[39m\] \\$ "' >> /etc/profile.d/prompt.sh

## set local timezone
logline "06.02 set local timezone"
echo -n "What timezone do you want (enter for UTC) =>"
read timezone
if [ "$timezone" == "" ]; then
	timedatectl set-timezone UTC
else
	timedatectl set-timezone $timezone
fi

logline "06.03 Chrony server as NTP"
dnf install -y chrony
systemctl start chronyd
# systemctl status chronyd
systemctl enable chronyd

logline "06.04 Python 3 - possibly already installed"
dnf -y install python3

### yum fortune and cowsay
logline "06.04 install fortune and cowsay"
# fortune is now a python app (fortune-mod is no longer distributed and a pain to cmake)
pip3 install fortune
git clone https://github.com/bmc/fortunes.git /usr/local/share/fortunes
yum -y install cowsay
echo "fortune /usr/local/share/fortunes/fortunes | cowsay -W 100 -f small" >/etc/profile.d/cowsay.sh

logline "06.05 additional yum installs"
dnf install -y rsync

logline "06.99 global settings END"
 

