#!/bin/bash

. ${BASH_SOURCE%/*}/00_settings

logline "06.00 global settings START"
# color prompt
logline "06.01 color prompt"
echo 'export PS1="\[\e[31;1m\]\h \[\e[0;34m\]\w\[\e[39m\] \[\e[0;32m\]\u\[\e[39m\] \\$ "' >> /etc/profile.d/prompt.sh

## set local timezone
logline "06.02 set timezone"
timedatectl set-timezone Europe/Amsterdam

logline "06.03 Chrony server as NTP"
dnf install chrony
systemctl start chronyd
# systemctl status chronyd
systemctl enable chronyd

### yum fortune and cowsay
#logline "06.04 install fortune and cowsay"
#yum -y install fortune-mod cowsay
#echo "fortune | cowsay -W 100 -f small" >/etc/profile.d/cowsay.sh

logline "06.99 global settings END"
 

