#!/bin/bash

. ${BASH_SOURCE%/*}/00_settings

logline "07.00 install php7.1 from remi"

logline "07.01 yum php"
## yum PHP 7.1 and start fpm
yum -d1 -y install php71-php-fpm php71-php-cli php71-php-mysqlnd php71-php-mcrypt
yum -d1 -y install  php71-php-pecl-imagick php71-php-pear  php71-php-mbstring
yum -d1 -y install  php71-php-common

## make php available without '71'
ln -s /usr/bin/php71 /usr/bin/php

logline "07.02 php.ini changes (short open tags, expose off, max exec time, memory limit, date.timezone, fix_pathinfo)"
phpini=`php71 --ini | grep Loaded | grep -o -e '/etc.*'`
echo "PHP ini file at $phpini"
phpinitemp=`mktemp`
cat $phpini |
	sed -e "s/short_open_tag = Off/short_open_tag = On/" | 
	sed -e "s/expose_php = On/expose_php = Off/" |
	sed -r "s/max_execution_time = [0-9]+/max_execution_time = 360/" |
	sed -r "s/memory_limit = [0-9]+M/memory_limit = 512M/" |
        sed -e "s/;date.timezone =/date.timezone = Europe\/Amsterdam/" |
	sed -r "s/;cgi.fix_pathinfo=[0-9]/cgi.fix_pathinfo=0/" 	>$phpinitemp
mv -f $phpinitemp $phpini

logline "07.03 fpm service"
## enable php7.1 fpm service
systemctl enable php71-php-fpm
service php71-php-fpm start

logline "07.04 composer"
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/bin/composer


logline "07.99 php END"


