#!/bin/bash

. ${BASH_SOURCE%/*}/00_settings

logline "07.00 install php7.1 from remi"

logline "07.01 yum php"
## yum PHP 7.1 and start fpm
yum -d1 -y install php74-php-fpm php74-php-cli php74-php-mysqlnd php74-php-mcrypt
yum -d1 -y install  php74-php-pecl-imagick php74-php-mbstring php74-php-pecl-zip php74-php-xml php74-php-bcmath
#php71-php-pear
yum -d1 -y install  php74-php-common php74-php-gd

## make php available without '74' (could do yum-config-manager --enable remi-php74;yum install php-cli.. << !!!! NOO this installs an OTHER php7.4 on /usr/bin)
## NOO dont do this: https://stackoverflow.com/questions/48682572/centos-installed-php72-but-command-line-php-isn-not-working/48683067
ln -s /usr/bin/php74 /usr/bin/php

logline "07.02 php.ini changes (short open tags, expose off, max exec time, memory limit, date.timezone, fix_pathinfo)"
phpini=`php74 --ini | grep Loaded | grep -o -e '/etc.*'`
echo "PHP ini file at $phpini"
phpinitemp=`mktemp`
# make some changes to the php.ini (you might tweak this a little)
cat $phpini |
	sed -e "s/short_open_tag = Off/short_open_tag = On/" | 
	sed -e "s/expose_php = On/expose_php = Off/" |
	sed -r "s/max_execution_time = [0-9]+/max_execution_time = 360/" |
	sed -r "s/memory_limit = [0-9]+M/memory_limit = 512M/" |
	sed -r "s/upload_max_filesize = [0-9]+M/upload_max_filesize = 12M/" |
        sed -e "s/;date.timezone =/date.timezone = Europe\/Amsterdam/" |
	sed -r "s/;cgi.fix_pathinfo=[0-9]/cgi.fix_pathinfo=0/" 	>$phpinitemp
mv -f $phpinitemp $phpini

logline "07.03 fpm service"
#phpfpmconf=/etc/opt/remi/php74/php-fpm.d/www.conf
phpconfdir=`php74 --ini | grep "Configuration File" | grep "Path" | grep -o -e '/etc.*'`
phpfpmconf=$phpconfdir/php-fpm.d/www.conf
phpfpmconftemp=`mktemp`
# use tcp for fastcgi and change user/group to nginx to make it equal to nginx service
cat $phpfpmconf |
  sed -e "s/listen =/\nlisten=127.0.0.1:9000\n;listen =/" |
  sed -e "s/user =/\nuser = nginx\n;user =/" |
  sed -e "s/group =/\ngroup = nginx\n;group =/" >$phpfpmconftemp
mv -f $phpfpmconftemp $phpfpmconf

## enable php fpm service
systemctl enable php74-php-fpm
service php74-php-fpm start

logline "07.04 composer"
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/bin/composer


logline "07.99 php END"


