#!/bin/bash

. ${BASH_SOURCE%/*}/00_settings

logline "11.00 git repository START"

logline "11.01 create repo dir"
## not much to do here. Everything is done in addvhost

if [ -z "$username" ]; then
	username=`ls /home`
fi
su -c "mkdir /home/$username/git" $username

logline "11.02 create /var/www for laravel apps"
mkdir -p /var/www

echo "The repos are created when addvhost is called (in ~/bin of $username)"

logline "11.99 git repo END"

