#!/bin/bash

. ${BASH_SOURCE%/*}/00_settings

logline "11.00 laravel START"

logline "11.01 create /var/www for laravel apps using Zero Downtime Deploy"

mkdir -p /var/www
myip=`curl -s ifconfig.me`

logline "11.02 create a simple (github/laravel/laravel) site on http://$myip using addzhost?"

echo -n "A default laravel webite (https://github.com/laravel/laravel) is optional. Install default webite @ http://$myip [Y/n]=>" && read dolaravelwebsite
if [ ! "$dolaravelwebsite" == "n" ]; then
  # use simple git clone for demo website
  # use laravel 8.6.12 as this runs with php7.4-8.1
  su - $username addzhost $myip https://github.com/laravel/laravel.git v8.6.12
fi

echo "!!! Use addzhost to add projects (located in ~/bin of $username)"

logline "11.99 laravel END"

