#!/bin/bash

. ${BASH_SOURCE%/*}/00_settings

logline "12.00 redis START"

logline "12.01 Redis Server install"
echo -n "redis installation is optional. Install Redis [Y/n]=>" && read doredis
if [ ! "$doredis" == "n" ]; then
	logline "12.02 Installing redis"
	yum -d1 -y install redis
	systemctl enable redis
	service redis start
fi

logline "12.99 redis END"

