#!/bin/bash
echo "##########################################################"
echo "Centos server install -- FULL SETUP"
echo "##########################################################"

. ./parts/01_user_create
. ./parts/02_set_hostname
. ./parts/03_repos_yums
. ./parts/04_root_password
. ./parts/05_security
. ./parts/06_global_settings
. ./parts/07_php
. ./parts/08_node_npm
. ./parts/09_mariadb_mysql
. ./parts/10_nginx
. ./parts/11_gitrepo

echo "##########################################################"
echo "FULL setup ready"
echo "##########################################################"
echo "Log out as root now, and never log in as root again."
echo "Log in as $username now"



