#!/bin/bash
if [ -z $1 ]; then
	echo "Usage: newversion x.y.z  -> x.y.z+1"
	echo " 1.3.4 -> 1.3.5"
	echo " 1.3.9 -> 1.4.0"
	echo " 1.3.09 -> 1.3.10 "
	echo " -x option -> 1.3.9 -> 1.3.10 "
	exit
fi
OVERFLOW=1
if [ "$1" == "-x" ]; then
	OVERFLOW=0
	shift
fi
# http://stackoverflow.com/questions/8653126/how-to-increment-version-number-in-a-shell-script
# NF=number of fields
# OFS = object field separator
if [ $OVERFLOW == 0 ]; then
	NEWVER=`echo $1 | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{$NF=sprintf("%0*d", length($NF), ($NF+1)); print}'`
else
	NEWVER=`echo $1 | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}'`
fi
echo $NEWVER
